version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=nami-url-shortener
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=docker
    ports:
      - "6379:6379"

volumes:
  postgres_data: {}
  redis_data: {}
